---
apiVersion: v1
kind: Service
metadata:
  name: es-master
  labels:
    name: es-master
spec:
  ports:
  - name: p92
    port: 9300
    targetPort: 9300
  - name: p93
    port: 9200
    targetPort: 9200
    nodePort: 30099
  clusterIP: None
  selector:
    role: es-master
  type: NodePort
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: es-master
spec:
  replicas: 1 
  selector:
    matchLabels:
      role: es-master
      petset: es-master
  serviceName: es-master
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        role: es-master
        petset: es-master
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: es-master
          securityContext:
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
          image: 10.39.0.118/xiaoyuchen/elasticsearch:test  
          imagePullPolicy: Always
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: "CLUSTER_NAME"
            value: "myesdb"
          - name: NODE_MASTER
            value: "true"
          - name: NODE_DATA
            value: "false"
          - name: HTTP_ENABLE
            value: "true"
          - name: ES_HEAP_SIZE
            value: "256m"
          - name: NETWORK_HOST
            value: "0.0.0.0"
          - name: ELASTICSEARCH_DISCOVERY_SERVICE_HOST
            value: "es-master"
          - name: ELASTICSEARCH_DISCOVERY_SERVICE_PORT
            value: "9300"
          ports:
          - containerPort: 9300
            name: transport
            protocol: TCP
          - containerPort: 9200
            name: tran
            protocol: TCP
          volumeMounts:
          - name: storage
            mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
