apiVersion: v1
kind:   ReplicationController
metadata:
  name: rbd
  labels:
    app: rbd-demo
spec:
  replicas: 1
  selector:
    app: rbd-demo
  template:
    metadata:
      labels:
        app: rbd-demo
    spec:
        containers:
        - name: demo
          image: busybox
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /mnt
            name: mypd
        volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: ceph-claim

